<a href="https://colab.research.google.com/github/Preethivk15/BENZKART/blob/main/deep_learning_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier


In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Datasets/Breast cancer-wisconsin.csv")

In [ ]:
df

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  texture_worst  perimeter_worst  area_worst  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  diagnosis  
0                  0.2654          0.4601                  0.11890          M  
1                  0.1860          0.2750                  0.08902          M  
2                  0.2430          0.3613                  0.08758          M  
3                  0.2575          0.6638                  0.17300          M  
4                  0.1625          0.2364        

In [ ]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [ ]:
df.isnull()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          False         False           False      False            False   
1          False         False           False      False            False   
2          False         False           False      False            False   
3          False         False           False      False            False   
4          False         False           False      False            False   
..           ...           ...             ...        ...              ...   
564        False         False           False      False            False   
565        False         False           False      False            False   
566        False         False           False      False            False   
567        False         False           False      False            False   
568        False         False           False      False            False   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0               False           False                False          False   
1               False           False                False          False   
2               False           False                False          False   
3               False           False                False          False   
4               False           False                False          False   
..                ...             ...                  ...            ...   
564             False           False                False          False   
565             False           False                False          False   
566             False           False                False          False   
567             False           False                False          False   
568             False           False                False          False   

     fractal_dimension_mean  ...  texture_worst  perimeter_worst  area_worst  \
0                     False  ...          False            False       False   
1                     False  ...          False            False       False   
2                     False  ...          False            False       False   
3                     False  ...          False            False       False   
4                     False  ...          False            False       False   
..                      ...  ...            ...              ...         ...   
564                   False  ...          False            False       False   
565                   False  ...          False            False       False   
566                   False  ...          False            False       False   
567                   False  ...          False            False       False   
568                   False  ...          False            False       False   

     smoothness_worst  compactness_worst  concavity_worst  \
0               False              False            False   
1               False              False            False   
2               False              False            False   
3               False              False            False   
4               False              False            False   
..                ...                ...              ...   
564             False              False            False   
565             False              False            False   
566             False              False            False   
567             False              False            False   
568             False              False            False   

     concave points_worst  symmetry_worst  fractal_dimension_worst  diagnosis  
0                   False           False                    False      False  
1                   False           False                    False      False  
2                   False           False                    False      False  
3                   False           False                    False      False  
4                   False           False        

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   radius_mean              569 non-null    float64
 1   texture_mean             569 non-null    float64
 2   perimeter_mean           569 non-null    float64
 3   area_mean                569 non-null    float64
 4   smoothness_mean          569 non-null    float64
 5   compactness_mean         569 non-null    float64
 6   concavity_mean           569 non-null    float64
 7   concave points_mean      569 non-null    float64
 8   symmetry_mean            569 non-null    float64
 9   fractal_dimension_mean   569 non-null    float64
 10  radius_se                569 non-null    float64
 11  texture_se               569 non-null    float64
 12  perimeter_se             569 non-null    float64
 13  area_se                  569 non-null    float64
 14  smoothness_se            5

In [ ]:
from sklearn.preprocessing import StandardScaler

# Drop label column
X = df.drop(columns=['diagnosis'])
Y = df['diagnosis']

# Initialize scaler
scaler = StandardScaler()

# Fit on entire data and transform
X_scaled = scaler.fit_transform(X)

# Now split the scaled data
x_train, x_test, y_train, y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state=42)


In [ ]:
#Support Vector Machine Classifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svm_classifier = SVC()
svm_classifier.fit(x_train, y_train)
svm_predict = svm_classifier.predict(x_test)
svm_acc = accuracy_score(svm_predict, y_test)
print("SVM Test accuracy: {:.2f}%".format(svm_acc * 100))

SVM Test accuracy: 97.37%


In [ ]:
# Print classification report and confusion matrix for SVM model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("SVM Classification Report:\n", classification_report(y_test, svm_predict))
conf_matrix_svm = confusion_matrix(y_test, svm_predict)
print("SVM Confusion Matrix:\n", conf_matrix_svm)

SVM Classification Report:
               precision    recall  f1-score   support

           B       0.97      0.99      0.98        71
           M       0.98      0.95      0.96        43

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

SVM Confusion Matrix:
 [[70  1]
 [ 2 41]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier

#Random Forest Classifier
for i in range(100,1000,100):
  rf_classifier = RandomForestClassifier(n_estimators=i, random_state=42)
  rf_classifier.fit(x_train, y_train)
  rf_predict = rf_classifier.predict(x_test)

  rf_acc = accuracy_score(rf_predict, y_test)
  print("Random Forest Test accuracy: {:.2f}%".format(rf_acc * 100))

Random Forest Test accuracy: 96.49%
Random Forest Test accuracy: 96.49%
Random Forest Test accuracy: 96.49%
Random Forest Test accuracy: 96.49%
Random Forest Test accuracy: 96.49%
Random Forest Test accuracy: 96.49%
Random Forest Test accuracy: 96.49%
Random Forest Test accuracy: 96.49%
Random Forest Test accuracy: 96.49%


In [ ]:
# Print classification report and confusion matrix for RandomForest
print(classification_report(y_test, rf_predict))
conf_matrix = confusion_matrix(y_test, rf_predict)
print("Confusion Matrix:\n", conf_matrix)


              precision    recall  f1-score   support

           B       0.96      0.99      0.97        71
           M       0.98      0.93      0.95        43

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

Confusion Matrix:
 [[70  1]
 [ 3 40]]


In [ ]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
logistic_classifier = LogisticRegression(random_state=42)
logistic_classifier.fit(x_train, y_train)
logistic_predict = logistic_classifier.predict(x_test)
logistic_acc = accuracy_score(logistic_predict, y_test)
print("Logistic Regression Test accuracy: {:.2f}%".format(logistic_acc * 100))

Logistic Regression Test accuracy: 97.37%


In [ ]:
# Print classification report and confusion matrix for Logistic Regression
print("Logistic Regression Classification Report:\n", classification_report(y_test, logistic_predict))
conf_matrix_logistic = confusion_matrix(y_test, logistic_predict)
print("Logistic Regression Confusion Matrix:\n", conf_matrix_logistic)

Logistic Regression Classification Report:
               precision    recall  f1-score   support

           B       0.97      0.99      0.98        71
           M       0.98      0.95      0.96        43

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

Logistic Regression Confusion Matrix:
 [[70  1]
 [ 2 41]]


In [ ]:
#hyperparameters grid
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear', 'saga']
}

logistic_classifier = LogisticRegression(random_state=42)
grid_search = GridSearchCV(estimator=logistic_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_train, y_train)
best_params = grid_search.best_params_
print("Best Parameters:", best_params)
best_classifier = grid_search.best_estimator_
best_predict = best_classifier.predict(x_test)
best_acc = accuracy_score(best_predict, y_test)
print("Best Estimator Test accuracy: {:.2f}%".format(best_acc * 100))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which 

Best Parameters: {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}
Best Estimator Test accuracy: 99.12%


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [ ]:
# Print classification report and confusion matrix for the best estimator
print("Best Estimator Classification Report:\n", classification_report(y_test, best_predict))
conf_matrix_best = confusion_matrix(y_test, best_predict)
print("Best Estimator Confusion Matrix:\n", conf_matrix_best)


Best Estimator Classification Report:
               precision    recall  f1-score   support

           B       0.99      1.00      0.99        71
           M       1.00      0.98      0.99        43

    accuracy                           0.99       114
   macro avg       0.99      0.99      0.99       114
weighted avg       0.99      0.99      0.99       114

Best Estimator Confusion Matrix:
 [[71  0]
 [ 1 42]]


In [ ]:
#adaboost
from sklearn.ensemble import AdaBoostClassifier

for i in range(100, 1000, 100):
    adaboost_classifier = AdaBoostClassifier(n_estimators=i, random_state=42)
    adaboost_classifier.fit(x_train, y_train)
    adaboost_predict = adaboost_classifier.predict(x_test)

    adaboost_acc = accuracy_score(adaboost_predict, y_test)
    print("AdaBoost Test accuracy with {} estimators: {:.2f}%".format(i, adaboost_acc * 100))

AdaBoost Test accuracy with 100 estimators: 97.37%
AdaBoost Test accuracy with 200 estimators: 97.37%
AdaBoost Test accuracy with 300 estimators: 97.37%
AdaBoost Test accuracy with 400 estimators: 97.37%
AdaBoost Test accuracy with 500 estimators: 97.37%
AdaBoost Test accuracy with 600 estimators: 97.37%
AdaBoost Test accuracy with 700 estimators: 96.49%
AdaBoost Test accuracy with 800 estimators: 96.49%
AdaBoost Test accuracy with 900 estimators: 97.37%


In [ ]:
788# Print classification report and confusion matrix for the adaboost
from sklearn.metrics import classification_report
print("Best Estimator Classification Report:\n", classification_report(y_test,adaboost_predict))
conf_matrix_ada = confusion_matrix(y_test,adaboost_predict)
print("Adaboost Confusion Matrix:\n", conf_matrix_ada)

Best Estimator Classification Report:
               precision    recall  f1-score   support

           B       0.97      0.99      0.98        71
           M       0.98      0.95      0.96        43

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

Adaboost Confusion Matrix:
 [[70  1]
 [ 2 41]]


In [ ]:
#knn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(x_train, y_train)
knn_predict = knn_classifier.predict(x_test)
knn_acc = accuracy_score(knn_predict, y_test)
print("KNN Test accuracy: {:.2f}%".format(knn_acc * 100))


KNN Test accuracy: 94.74%


In [ ]:
# Print classification report and confusion matrix for knn
from sklearn.metrics import classification_report
print("Best Estimator Classification Report:\n", classification_report(y_test,knn_predict))
conf_matrix_ada = confusion_matrix(y_test,knn_predict)
print("Adaboost Confusion Matrix:\n", conf_matrix_ada)

Best Estimator Classification Report:
               precision    recall  f1-score   support

           B       0.96      0.96      0.96        71
           M       0.93      0.93      0.93        43

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

Adaboost Confusion Matrix:
 [[68  3]
 [ 3 40]]


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Assuming you have X_train, X_test, y_train, y_test already defined

# Initialize the GradientBoostingClassifier
gradient_boost_classifier = GradientBoostingClassifier()

# Fit the model on the training data
gradient_boost_classifier.fit(x_train, y_train)

# Make predictions on the test set
gb_predict = gradient_boost_classifier.predict(x_test)

# Calculate accuracy
gb_acc = accuracy_score(gb_predict, y_test)
print("Gradient Boosting Test Accuracy: {:.2f}%".format(gb_acc * 100))


Gradient Boosting Test Accuracy: 95.61%


In [ ]:
# Print classification report and confusion matrix for gradient boostinng
print("Gradient Boosting Classification Report:\n", classification_report(y_test, gb_predict))
conf_matrix_gb = confusion_matrix(y_test, gb_predict)
print("Gradient Boosting Confusion Matrix:\n", conf_matrix_gb)

Gradient Boosting Classification Report:
               precision    recall  f1-score   support

           B       0.96      0.97      0.97        71
           M       0.95      0.93      0.94        43

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

Gradient Boosting Confusion Matrix:
 [[69  2]
 [ 3 40]]


In [ ]:
#Decision tree
from sklearn.tree import DecisionTreeClassifier
decision_tree_classifier = DecisionTreeClassifier(random_state=42)
decision_tree_classifier.fit(x_train, y_train)
dt_predict = decision_tree_classifier.predict(x_test)
dt_acc = accuracy_score(dt_predict, y_test)
print("Decision Tree Test accuracy: {:.2f}%".format(dt_acc * 100))

Decision Tree Test accuracy: 94.74%


In [ ]:
# Print classification report and confusion matrix for Decision Tree
print("Decision Tree Classification Report:\n", classification_report(y_test, dt_predict))
conf_matrix_dt = confusion_matrix(y_test, dt_predict)
print("Decision Tree Confusion Matrix:\n", conf_matrix_dt)


Decision Tree Classification Report:
               precision    recall  f1-score   support

           B       0.96      0.96      0.96        71
           M       0.93      0.93      0.93        43

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

Decision Tree Confusion Matrix:
 [[68  3]
 [ 3 40]]


In [ ]:
#naive bayers
from sklearn.naive_bayes import GaussianNB
naive_bayes_classifier = GaussianNB()
naive_bayes_classifier.fit(x_train, y_train)
nb_predict = naive_bayes_classifier.predict(x_test)
nb_acc = accuracy_score(nb_predict, y_test)
print("Naive Bayes Test accuracy: {:.2f}%".format(nb_acc * 100))

Naive Bayes Test accuracy: 96.49%


In [ ]:
# Print classification report and confusion matrix for Naive Bayes
print("Naive Bayes Classification Report:\n", classification_report(y_test, nb_predict))
conf_matrix_nb = confusion_matrix(y_test, nb_predict)
print("Naive Bayes Confusion Matrix:\n", conf_matrix_nb)


Naive Bayes Classification Report:
               precision    recall  f1-score   support

           B       0.96      0.99      0.97        71
           M       0.98      0.93      0.95        43

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

Naive Bayes Confusion Matrix:
 [[70  1]
 [ 3 40]]


In [ ]:
import pickle

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [ ]:
with open('breast_cancer.pkl', 'wb') as file:
    pickle.dump(adaboost_classifier, file)

In [ ]:
from google.colab import files

# Download the saved model
files.download('breast_cancer.pkl')

# Download the saved scaler
files.download('scaler.pkl')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>